version: "3"
services:
  nerdl:
    build: ./tools/ner-dataset-labeler
    ports: 
      - 8080:80
  cpoint-pta:
    build: ./apps/cpoint-pta
    ports:
      - 8081:80
  chatbot-backend:
    build: ./apps/cpoint-pta-backend
    ports: 
      - 3000:3000