service: cpoint-pta-backend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: 'eu-west-1'
  apiGateway:
    shouldStartNameWithService: true

functions:
  detectIntent:
    handler: handler.detectIntent
    events: 
      - http: 
          method: get
          path: /detectIntent
